### ISSUE TITLE
Floating Panels Stick to the Right

### ISSUE THREAD

**Issue by nikolayarhangelov** [nikolayarhangelov/rcman#7]
There is a know issue with AvalonDock - https://github.com/xceedsoftware/wpftoolkit/issues/1119, which will always stick floating panels to the right. This means that Connections, Properties and Settings will show on the right as well.

**Comment by nikolayarhangelov** [comment]
Downgraded AvalonDock.

**Comment by Dirkster99** [comment]
Hi, not sure if its still relevent but I solved this and other issues in my own branch of AvalonDock (in case you want to upgrade to 3.4)
https://github.com/Dirkster99/AvalonDock

**Comment by nikolayarhangelov** [comment]
@Dirkster99 thanks, I will check it out!
